version: '3.7'

services:
    backend:
        build:
            context: .
        image: backend:latest
        container_name: backend
        restart: always
        env_file: .env
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        entrypoint: python main.py
        depends_on:
            - redis
    redis:
        image: "redis"
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        env_file: .env
        entrypoint: redis-server --requirepass ${REDIS_PWD}

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "8001:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - backend
            
